
#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parking?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: shawnye
    password: 7444
    driver-class-name: com.mysql.cj.jdbc.Driver

# Logger Config
logging:
    level:
      com.park: info


