INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('car', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('motorcycle', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('small bus', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('small bus', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('small bus', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('small bus', '0');
INSERT INTO `parking`.`parking_spaces` (`type`, `status`) VALUES ('small bus', '0');
